name: task1_cubit
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  persistent_bottom_nav_bar: ^6.2.1
  flutter_screenutil: ^5.9.3
  cupertino_icons: ^1.0.8
  # shared_preferences: ^2.5.3
  carousel_slider: ^5.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  liquid_swipe: ^3.1.0
  google_fonts: ^6.3.3
  device_preview: ^1.3.1
  # analyzer: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/mock_data/users.json
    - assets/mock_data/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
